---
# Title: UrBackup server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/01-urbackup-server.yml
#
# Description:
#   Playbook for UrBackup server
#   on a Ubuntu server.
#
- name: "Add repository"
  ansible.builtin.apt_repository:
    repo: ppa:uroni/urbackup
    state: present
    
- name: "Install APT packages"
  ansible.builtin.apt:
    pkg:
#    - nfs-common
#    - nfs-kernel-server
    - gnupg
    - urbackup-server
    update_cache: yes
    state: present

#- name: "Create NFS directory structure"
#  ansible.builtin.file:
#    path: "{{ urbackup_backup_path }}"
#    state: directory
#    owner: urbackup
#    group: urbackup
#    mode: 0755

#- name: "Mount NFS path for UrBackup"
#  ansible.posix.mount:
#    src: "{{ urbackup_nfs_path}}"
#    path: "{{ urbackup_backup_path }}"
#    opts: defaults
#    state: mounted
#    fstype: nfs4

- name: "ufw allow traffic on specific ports"
  community.general.ufw:
    rule: allow
    direction: "{{ item.dir }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - { dir: 'in', port: '55415', proto: 'tcp' }
    - { dir: 'out', port: '35623', proto: 'udp' }
