---
# Title: NFS share for UrBackup
#
# Author: Bitfinity-NL
# Owner: Bitfinity-NL
#
# File: tasks/common/storage-nfs.yml
#
# Description:
#   Configure NFS-share for UrBackup server. 
#   
- name: "Install APT packages"
  ansible.builtin.apt:
    pkg:
    - nfs-common
    update_cache: yes
    state: present

- name: "Ensure mountpoint '{{ urbackup_nfs_share_mountpoint }}' exists"
  ansible.builtin.file:
    path: "{{ urbackup_nfs_share_mountpoint }}"
    state: directory
    owner: root
    group: root
    mode: '0000'  # Disable writing for everyone, if mounting fails.

- name: "Mount NFS share '{{ urbackup_nfs_share_mountpoint }}' to '{{ urbackup_nfs_share_source }}' for UrBackup server"
  ansible.posix.mount:
    src: "{{ urbackup_nfs_share_source }}"
    path: "{{ urbackup_nfs_share_mountpoint }}"
    opts: defaults
    state: mounted
    fstype: nfs4

- name: "Correct permissions on '{{ urbackup_nfs_share_mountpoint}' when mounted"
  ansible.builtin.file:
    path: "{{ urbackup_nfs_share_mountpoint }}"
    state: directory
    owner: urbackup
    group: urbackup
    mode: '0755'
