---
# Title: UrBackup server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/docker/01-urbackup-server-docker.yml
#
# Description:
#   Taskfile for installing UrBackup server
#   on a Ubuntu server with docker.
#

- name: "Create NFS directory structure"
  ansible.builtin.file:
    path: "{{ urbackup_docker_backup_path }}"
    state: directory
    owner: urbackup
    group: urbackup
    mode: 0755
