---
# Title: UrBackup server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/docker/01-urbackup-server-docker.yml
#
# Description:
#   Taskfile for installing UrBackup server
#   on a Ubuntu server with docker.
#
- name: "Create group 'urbackup' for urbackup on host '{{ ansible_hostname }}'"
  ansible.builtin.group:
    name: urbackup
    state: present
    
- name: "Create user 'urbackup' for urbackup on host '{{ ansible_hostname }}'"
  ansible.builtin.user:
    name: urbackup
    shell: /bin/bash
    group: urbackup

- name: "Create directory '{{ urbackup_docker_backup_path }}' for the database on host structure on host '{{ ansible_hostname }}'"
  ansible.builtin.file:
    path: "{{ urbackup_docker_backup_path }}"
    state: directory
    owner: urbackup
    group: urbackup
    mode: '0750'
    
#- name: "Create directory '{{ urbackup_docker_backup_path }}' for backups on host structure on host '{{ ansible_hostname }}'"
#  ansible.builtin.file:
#    path: "{{ urbackup_docker_backup_path }}"
#    state: directory
#    owner: urbackup
#    group: urbackup
#    mode: '0750'

- name: "Create directory '/opt/urbackup' for urbackup docker on host '{{ ansible_hostname }}'"
  ansible.builtin.file:
    path: "/opt/urbackup"
    state: directory
    owner: root
    group: root
    mode: '0750'

- name: "Transfer template 'templates/docker/docker-compose.yml.j2' to '/opt/urbackup/docker-compose.yml' on host '{{ ansible_hostname }}'"
  ansible.builtin.template:
    src: templates/docker/docker-compose.yml.j2
    dest: /opt/urbackup/docker-compose.yml
    owner: root
    group: root
    mode: '0750'

- name: "Run docker-compose.yml for UrBackup on host '{{ inventory_hostname }}'"
  ansible.builtin.command: docker compose up -d
  args:
    chdir: /opt/urbackup

- name: "Install and configure Apache2 for UrBackup server (docker)"
  include_tasks: tasks/docker/02-apache2-docker.yml
